export const environment = {
    production: false,
    apiUrlGetCarriages: '/api/carriage',
    apiUrlPostCarriage: '/api/carriage',
    apiUrlPutCarriage: '/api/carriage/',
    apiLogout: '/api/logout',
    apiSignIn: '/api/signin',
    apiSignUp: '/api/signup',
    apiProfile: '/api/profile',
    apiProfilePassword: '/api/profile/password',
    apiUrlGetRideInformation: '/api/search/',
    apiUrlPostOrder: '/api/order',
    apiUrlStation: '/api/station',
    apiUrlRoute: '/api/route',
    apiUrlSearch: '/api/search',
    apiOrder: '/api/order',
    apiUsers: '/api/users',
    apiDeleteOrder: '/api/order/{orderId}',
};
